---
- name: Install Gitlab.
  ansible.builtin.apt:
    name: gitlab-ee
    state: present
  environment:
    EXTERNAL_URL: "http://{{ inventory_hostname }}"
    GITLAB_ROOT_PASSWORD: "{{ gitlab_admin_password }}"

- name: Reconfigure Gitlab for the first time.
  ansible.builtin.shell:
    cmd: gitlab-ctl reconfigure
    creates: /var/opt/gitlab/bootstrapped
  become: true
