- name: Setup a Gitlab runner.
  hosts: runner
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:  
    - ansible.builtin.script: "scripts/get_suffix.py '{{ inventory_hostname }}'"
      args:
        executable: python3
      delegate_to: localhost
      register: suffix_script
      changed_when: False
      become: False
    
    - ansible.builtin.set_fact:
        suffix: "{{ suffix_script.stdout | trim }}"
       
    - name: Check if the runner is already setup.
      ansible.builtin.stat:
        path: /etc/systemd/system/gitlab-runner.service
      register: runner_service

  tasks:
    - name: Setup the runner.
      ansible.builtin.include_role: 
        name: local.gitlab-runner
      when: not runner_service.stat.exists