---
- name: Add all runners to the gitlab server.
  hosts: runner
  become: yes

  pre_tasks:
    - ansible.builtin.script: "scripts/get_suffix.py '{{ inventory_hostname }}'"
      args:
        executable: python3
      delegate_to: localhost
      register: suffix_script
      changed_when: False
      become: False
    
    - ansible.builtin.set_fact:
        suffix: "{{ suffix_script.stdout | trim }}"
  roles:
    - local.connect-runner
