---
- name: Proxmox subscription repository auskommentieren.
  ansible.builtin.replace:
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: "^deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
    replace: "# deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"

- name: Proxmox no-subscription repository hinzufügen.
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: "deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
    state: present